# Pour déclencher ce workflow : git tag v1.X && git push origin v1.X
# OU en une seule ligne : git tag v1.X && git push origin --tags
name: Release on tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ZIPs (Windows full and Hosted PHP minimal)
        shell: bash
        run: |
          set -euo pipefail
          VERSION="${GITHUB_REF_NAME}"
          mkdir -p dist
          echo "Building full Windows package ZIP…"
          zip -r "dist/RGSX_Sources_Manager_Windows_${VERSION}.zip" . \
            -x ".git/*" ".git/**" ".github/*" ".github/**" ".gitignore"

          echo "Building hosted PHP minimal ZIP…"
          mkdir -p dist/min/assets/lang
          cp -f data/rgsx_sources_manager.php dist/min
          cp -rf data/assets/lang/* dist/min/assets/lang/
          cp -f data/assets/favicon_rgsx.ico dist/min/assets/ || true
          # Note: If you also want Batocera lists, uncomment the next line
          # cp -f data/assets/batocera_systems.json dist/min/assets/
          (cd dist/min && zip -r "../RGSX_Sources_Manager_PHP_${VERSION}.zip" .)

          echo "Creating stable-named copies for latest download links…"
          cp -f "dist/RGSX_Sources_Manager_Windows_${VERSION}.zip" "dist/RGSX_Sources_Manager_Windows.zip"
          cp -f "dist/RGSX_Sources_Manager_PHP_${VERSION}.zip" "dist/RGSX_Sources_Manager_PHP.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
